name: "Unit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: 🧰 Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: ⬇️ Install dependencies
      run: |
        sudo apt update
        sudo apt install -y       \
            build-essential       \
            gcc-11                \
            g++-11                \
            lld                   \
            ${PKGCONF:-}          \
            cmake                 \
            make                  \

    - name: 🛠️ Build
      run: |
        mkdir -p build
        cd build
        CC=gcc-11 CXX=g++-11 cmake              \
          -DCMAKE_C_FLAGS="-fuse-ld=lld"        \
          -DCMAKE_CXX_FLAGS="-fuse-ld=lld"      \
          ..
        make -j4 pattern_language_tests

    - name: 🧪 Perform Unit Tests
      run: |
        cd build
        ctest